In [1]:
import numpy as np

1、创建从0到9的一维数组

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2、创建一个3×3的二维数组，值域为0到8 

In [3]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3、将一维数组np.arange(10)转换为2行的二维数组

In [4]:
a = np.arange(10)
b = a.reshape(2, -1)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4、将数组a = np.arange(10).reshape(2,-1)和数组b = np.repeat(1, 10).reshape(2,-1)垂直堆叠

In [5]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
c = np.vstack((a, b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5、将数组a = np.arange(10).reshape(2,-1)和数组b = np.repeat(1, 10).reshape(2,-1)水平堆叠 

In [6]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
c = np.hstack((a, b))
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

6、找到二维数组np.arange(9).reshape(3,3)每一行中的最大值

In [7]:
a = np.arange(9).reshape(3, 3)
b = np.max(a, axis=1)
b

array([2, 5, 8])

In [8]:
a = np.arange(9).reshape(3, 3)
b = np.max(a, axis=1)
b

array([2, 5, 8])

2、创建一个3×3的二维数组，值域为0到8 

In [9]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3、将一维数组np.arange(10)转换为2行的二维数组

In [10]:
a = np.arange(10)
b = a.reshape(2, -1)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4、将数组a = np.arange(10).reshape(2,-1)和数组b = np.repeat(1, 10).reshape(2,-1)垂直堆叠

In [11]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
c = np.vstack((a, b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5、将数组a = np.arange(10).reshape(2,-1)和数组b = np.repeat(1, 10).reshape(2,-1)水平堆叠 

In [12]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
c = np.hstack((a, b))
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

6、找到二维数组np.arange(9).reshape(3,3)每一行中的最大值

In [13]:
a = np.arange(9).reshape(3, 3)
b = np.max(a, axis=1)
b

array([2, 5, 8])